name: Validate entries in index.json file

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Validate notebooks and index.json file
      run: |
        python .ci/scripts/validate_entries.py